import { useEffect, useRef, useState, useId, type ReactNode } from 'react';
import { getTask } from './tasks';
import { STORAGE_KEY, emptyStore, makeRound, startTrial, pauseTrial, resumeTrial, advanceToAnswer, advanceToRating, finishTrial, scoreTrial, conditionSummary, roundWarnings, restoreStore, exportData, newTrial, type Store, type Round, type Trial } from './engine';

type Screen = 'home' | 'setup' | 'practice' | 'practiceFeedback' | 'ready' | 'run' | 'results';
const labels = { A: '連続した文章', B: 'まとまりで区切った文章' };
const formatTime = (ms: number | null) => ms === null ? '—' : `${Math.round(ms / 1000)}秒`;
const formatScore = (correct:number, answered:number) => answered ? `${correct} / ${answered}` : '—';
function Arrow({direction='right'}:{direction?:'right'|'left'}) { return <span aria-hidden="true">{direction==='right'?'↗':'←'}</span>; }
function Brand() { return <span className="brand"><span className="brand-mark" aria-hidden="true"><i/><i/><i/></span>explain<span className="brand-light">fit</span><span className="prototype-tag">PROTOTYPE</span></span>; }
function Modal({title, children, onClose}:{title:string; children:ReactNode; onClose:()=>void}) {
  const ref = useRef<HTMLDialogElement>(null); const titleId=useId();
  useEffect(()=>{ const dialog=ref.current; dialog?.showModal(); return ()=>dialog?.close(); },[]);
  return <dialog ref={ref} aria-labelledby={titleId} onCancel={onClose} className="modal"><div className="modal-top"><h2 id={titleId}>{title}</h2><button className="icon-button" aria-label="閉じる" onClick={onClose}>×</button></div>{children}</dialog>;
}
function Scale({label, description, low, high, value, onChange}:{label:string;description?:string;low:string;high:string;value:number|null;onChange:(n:number|null)=>void}) {
  return <fieldset className="scale"><legend>{label}</legend>{description&&<p className="muted small">{description}</p>}<div className="scale-options">{Array.from({length:7},(_,i)=>i+1).map(n=><label key={n} className={value===n?'chosen':''}><input type="radio" name={label} checked={value===n} onChange={()=>onChange(n)}/><span>{n}</span></label>)}</div><div className="scale-ends"><span>1 · {low}</span><span>7 · {high}</span></div><button className="text-button small" onClick={()=>onChange(null)} type="button">回答しない{value===null?'（未回答）':''}</button></fieldset>;
}
function Passage({trial}:{trial:Trial}) {
  const task=getTask(trial.taskId);
  return <article className="passage-card"><div className="passage-label"><span>説明</span><span>回答中も参照できます</span></div><h2>{task.title}</h2><div className="passage">{trial.condition==='A'?<p>{task.paragraphs.join('')}</p>:task.paragraphs.map((p,i)=><p key={i}>{p}</p>)}</div></article>;
}
export default function App() {
  const [loaded] = useState(()=>{try{const raw=localStorage.getItem(STORAGE_KEY);return {store:restoreStore(raw,Date.now()),error:'',raw};}catch{return {store:emptyStore(),raw:null,error:'保存データを読み込めませんでした。元のデータは上書きしていません。リセットすると、このブラウザの記録を削除して開始できます。'};}});
  const [store,setStore]=useState<Store>(loaded.store);
  const [storageError,setStorageError]=useState(loaded.error);
  const [saveWarning,setSaveWarning]=useState('');
  const [writeBlocked,setWriteBlocked]=useState(false);
  const lastSaved=useRef<string|null>(loaded.raw);
  const conflictMessage='別のタブで記録が更新・削除されたため、この画面からの保存を止めました。ページを再読み込みして最新の記録を開いてください。';
  const [screen,setScreen]=useState<Screen>('home');
  const [selectedId,setSelectedId]=useState<string|null>(null);
  const [familiarity,setFamiliarity]=useState<Round['familiarity']>('new');
  const [practiceIndex,setPracticeIndex]=useState(0);
  const [practice,setPractice]=useState<Trial>(newTrial('practice-1','A'));
  const [breakOpen,setBreakOpen]=useState(false);
  const [confirm,setConfirm]=useState<'reset'|'stop'|'missing'|'skip'|null>(null);
  const [privacy,setPrivacy]=useState(false);
  const [showReview,setShowReview]=useState(false);
  const round=store.rounds.find(r=>r.id===selectedId);
  const trial=screen==='practice'?practice:round?.trials[round.index];
  const isTask=(screen==='run'||screen==='practice')&&!breakOpen;
  const active=store.rounds.find(r=>r.status!=='complete');
  const initial=store.rounds.find(r=>r.set==='initial');
  const retest=store.rounds.find(r=>r.set==='retest');
  const today=(()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;})();
  const canRetest=initial?.status==='complete'&&!retest&&initial.day!==today;
  useEffect(()=>{if(storageError||writeBlocked)return;try{if(localStorage.getItem(STORAGE_KEY)!==lastSaved.current){setWriteBlocked(true);setSaveWarning(conflictMessage);return;}const raw=JSON.stringify(store);localStorage.setItem(STORAGE_KEY,raw);lastSaved.current=raw;setSaveWarning('');}catch{setSaveWarning('このブラウザに保存できません。画面を閉じる前にJSONを書き出してください。');}},[store,storageError,writeBlocked]);
  useEffect(()=>{const changed=(event:StorageEvent)=>{if((event.key===STORAGE_KEY||event.key===null)&&event.newValue!==lastSaved.current){setWriteBlocked(true);setSaveWarning(conflictMessage);}};window.addEventListener('storage',changed);return()=>window.removeEventListener('storage',changed);},[]);
  useEffect(()=>{window.scrollTo({top:0,behavior:'instant'});},[screen,round?.index,practiceIndex]);
  const updateRound=(fn:(r:Round)=>Round)=>setStore(s=>({...s,rounds:s.rounds.map(r=>r.id===selectedId?fn(r):r)}));
  const changeTrial=(fn:(t:Trial)=>Trial)=>{if(screen==='practice')setPractice(fn);else updateRound(r=>({...r,trials:r.trials.map((t,i)=>i===r.index?fn(t):t)}));};
  useEffect(()=>{
    if(!isTask)return;
    const hidden=()=>{if(document.hidden){if(screen==='practice')setPractice(t=>pauseTrial(t,Date.now(),'hidden'));else setStore(s=>({...s,rounds:s.rounds.map(r=>r.id===selectedId?{...r,trials:r.trials.map((t,i)=>i===r.index?pauseTrial(t,Date.now(),'hidden'):t)}:r)}));}};
    document.addEventListener('visibilitychange',hidden);
    return ()=>document.removeEventListener('visibilitychange',hidden);
  },[isTask,screen,selectedId]);
  const startRound=(set:'initial'|'retest')=>{
    const random=new Uint32Array(1);crypto.getRandomValues(random);
    const created=makeRound(set,random[0],Date.now(),familiarity,store.rounds.flatMap(r=>r.trials.map(t=>t.taskId)),{width:innerWidth,height:innerHeight,language:navigator.language});
    created.trials[0]=startTrial(created.trials[0],Date.now());
    setStore(s=>({...s,rounds:[...s.rounds,created]}));setSelectedId(created.id);setBreakOpen(false);setScreen('run');
  };
  const beginPractice=()=>{setPracticeIndex(0);setPractice(startTrial(newTrial('practice-1','A'),Date.now()));setScreen('practice');};
  const resumeRound=(r:Round)=>{
    setSelectedId(r.id);setStore(s=>({...s,rounds:s.rounds.map(x=>x.id===r.id?{...x,status:'active',trials:x.trials.map((t,i)=>i===x.index?(t.openedAt?resumeTrial(t,Date.now()):startTrial(t,Date.now())):t)}:x)}));setBreakOpen(false);setScreen('run');
  };
  const finish=()=>{
    if(!trial)return;
    if(screen==='practice'){setPractice(t=>finishTrial(t,Date.now()));setScreen('practiceFeedback');return;}
    if(!round)return;
    const last=round.index===7;
    updateRound(r=>{if(r.trials[r.index].taskId!==trial.taskId || r.trials[r.index].phase!=='rating' || r.trials[r.index].paused)return r;return {...r,trials:r.trials.map((t,i)=>i===r.index?finishTrial(t,Date.now()):i===r.index+1&&r.index!==3?startTrial(t,Date.now()):t), index:last?7:r.index+1,status:last?'complete':'active',completedAt:last?new Date().toISOString():null};});
    if(last)setScreen('results');else if(round.index===3)setBreakOpen(true);
  };
  const exportJson=()=>{const blob=new Blob([exportData(store)],{type:'application/json;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`explain-fit-${today}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  const reset=()=>{try{localStorage.removeItem(STORAGE_KEY);lastSaved.current=null;setWriteBlocked(false);setStore(emptyStore());setStorageError('');setSaveWarning('');setSelectedId(null);setScreen('home');setConfirm(null);}catch{setSaveWarning('記録を削除できませんでした。ブラウザのサイトデータ設定を確認してください。');setConfirm(null);}};
  const stop=()=>{updateRound(r=>({...r,status:'stopped',trials:r.trials.map((t,i)=>i===r.index?pauseTrial(t,Date.now(),'exit'):t)}));setConfirm(null);setScreen('results');};
  const readComplete=()=>{changeTrial(t=>advanceToAnswer(t,Date.now()));requestAnimationFrame(()=>(()=>{const el=document.getElementById('questions');el?.scrollIntoView({behavior:'smooth',block:'start'});el?.focus({preventScroll:true});})());};
  const submitAnswers=()=>{if(trial?.answers.some(a=>a===null))setConfirm('missing');else changeTrial(t=>advanceToRating(t,Date.now()));};
  const showPrivacy=()=>{if(isTask&&trial?.openedAt)changeTrial(t=>pauseTrial(t,Date.now(),'manual'));setPrivacy(true);};
  const goHome=()=>{if(isTask&&trial?.openedAt)changeTrial(t=>pauseTrial(t,Date.now(),'exit'));setScreen('home');};

  return <div className="app-shell"><header className="site-header"><button className="brand-button" onClick={goHome} aria-label="ホームへ"><Brand/></button><div className="header-right"><span className="local-pill"><span/>この端末に保存</span><button className="icon-button help-button" onClick={showPrivacy} aria-label="データとこの試作について">?</button></div></header>
    {(storageError||saveWarning)&&<div className="global-warning" role="alert">{storageError||saveWarning}{storageError&&<button onClick={()=>setConfirm('reset')}>保存データをリセット</button>}</div>}
    <main>
      {screen==='home'&&<>
        <section className="hero"><div className="hero-copy"><div className="eyebrow"><span/> A SMALL EXPERIMENT, FOR YOU</div><h1>説明の、<br/>ちょうどいいを<br/><span>探してみよう。</span></h1><p className="hero-description">同じ言葉でも、区切り方で読み心地は変わる。<br className="desktop-break"/>小さな比較から、自分に役立つ説明のヒントを。</p><div className="hero-actions">{active?<button className="button primary" onClick={()=>resumeRound(active)} disabled={!!storageError}>途中から続ける <Arrow/></button>:!initial?<button className="button primary" onClick={()=>setScreen('setup')} disabled={!!storageError}>比較をはじめる <Arrow/></button>:canRetest?<button className="button primary" onClick={()=>setScreen('setup')}>未見の課題で再確認 <Arrow/></button>:<button className="button primary" onClick={()=>{setSelectedId((retest??initial).id);setScreen('results');}}>記録を見る <Arrow/></button>}<span className="hero-meta">{active?`${active.trials.filter(t=>t.phase==='done').length} / 8 課題を完了`:'8課題 · 約15〜20分（目安）'}</span></div>{initial&&!retest&&!canRetest&&!active&&<p className="small muted">再確認の8課題は、別日に取り組めます。</p>}<div className="hero-note"><span aria-hidden="true">↳</span> 能力や学習タイプを診断するものではありません</div></div>
        <div className="hero-visual" aria-hidden="true"><div className="visual-top"><span>ONE TEXT. TWO RHYTHMS.</span><span>01 / 02</span></div><div className="paper paper-one"><span className="paper-index">01</span><div className="paper-title">ひと続きに読む</div><div className="fake-lines">{[100,100,94,100,100,86,100,73].map((n,i)=><i key={i} style={{width:`${n}%`}}/>)}</div></div><div className="paper paper-two"><span className="paper-index">02</span><div className="paper-title">まとまりごとに読む</div><div className="fake-lines grouped">{[100,88,100,100,77,100,83].map((n,i)=><i key={i} style={{width:`${n}%`}}/>)}</div></div><div className="visual-caption"><span className="spark">✳</span><span>言葉はそのまま。<br/>変えるのは、文章の区切りだけ。</span></div></div></section>
        <section className="journey-section"><div className="section-heading"><h2>比べるのは、こんなこと。</h2><span>HOW IT WORKS</span></div><div className="journey-grid"><div className="journey-card"><span className="step-number">01</span><div><h3>架空のルールを読む</h3><p>予備知識が要らない短い説明を、<br/>2つの表示形式で読みます。</p></div></div><div className="journey-card"><span className="step-number">02</span><div><h3>説明を使って答える</h3><p>説明を見返しながら、<br/>内容確認と応用の4問に回答。</p></div></div><div className="journey-card"><span className="step-number">03</span><div><h3>いくつかの面から振り返る</h3><p>正答・時間・努力・好みを、<br/>混ぜずに、並べて見ます。</p></div></div></div></section>
        <section className="home-bottom"><span className="leaf-icon" aria-hidden="true">⌁</span><p><strong>あなたのペースで、大丈夫。</strong><br/>4課題のあとにひと休み。途中保存もできます。</p><button className="text-button" onClick={showPrivacy}>データの扱いと限界 <Arrow/></button></section>
        {store.rounds.length>0&&<section className="saved-section"><h2>この端末の記録</h2>{store.rounds.map(r=><button className="saved-row" key={r.id} onClick={()=>{setSelectedId(r.id);setScreen('results');}}><span>{r.set==='initial'?'初回の比較':'未見セットの再確認'}<small>{r.day} · {r.trials.filter(t=>t.phase==='done').length} / 8 課題</small></span><span>{r.status==='complete'?'結果を見る':'途中の記録'} →</span></button>)}</section>}
      </>}
      {screen==='setup'&&<section className="narrow flow-page"><button className="text-button" onClick={goHome}>← 戻る</button><div className="eyebrow">BEFORE YOU BEGIN</div><h1>まず、準備を少し。</h1><p className="lead">速さを競うものではありません。<br/>落ち着いて取り組めるときに、はじめましょう。</p><div className="info-panel"><h3>今回すること</h3><ul><li>説明は、回答している間も見返せます。</li><li>1課題に4問。8課題の中で2つの表示形式を比べます。</li><li>中断すると計時が止まります。タブを離れた場合も一時停止します。</li><li>本番の正解は、別日の再確認が終わってから表示します。</li></ul></div><fieldset className="familiarity"><legend>こうした架空のルール問題に、どのくらい慣れていますか？</legend>{([['new','ほとんど取り組んだことがない'],['some','少し取り組んだことがある'],['many','よく取り組む']] as const).map(([v,l])=><label key={v}><input type="radio" name="familiarity" checked={familiarity===v} onChange={()=>setFamiliarity(v)}/>{l}</label>)}</fieldset><div className="privacy-inline"><span aria-hidden="true">⌂</span><p>回答と時間はこのブラウザだけに保存します。複数のタブでは同時に取り組まないでください。外部への送信・ログイン・解析サービスはありません。自分で削除するか、サイトデータを消すまで残ります。</p></div>{canRetest?<button className="button primary full" onClick={()=>startRound('retest')}>再確認の8課題をはじめる <Arrow/></button>:<><button className="button primary full" onClick={beginPractice}>2つの練習で流れをつかむ <Arrow/></button><button className="text-button centered" onClick={()=>setScreen('ready')}>練習を済ませたので、本番の説明へ</button></>}</section>}
      {screen==='ready'&&<section className="narrow flow-page ready-page"><div className="round-symbol" aria-hidden="true">✳</div><div className="eyebrow">YOUR FIRST ROUND</div><h1>準備ができたら、<br/>8つの小さな比較へ。</h1><p className="lead">わからない問題は未回答でも大丈夫。<br/>回答後には、考える努力と表示の好みを聞きます。</p><div className="ready-facts"><span><b>8</b>課題</span><span><b>4</b>問 / 課題</span><span><b>1</b>途中休憩</span></div><p className="small muted">スタートすると最初の説明が表示され、計時が始まります。</p><button className="button primary full" onClick={()=>startRound('initial')}>最初の課題をはじめる <Arrow/></button></section>}
      {isTask&&trial&&<section className="task-page"><div className="task-topline"><div><span className="eyebrow">{screen==='practice'?'PRACTICE':round?.set==='retest'?'SECOND ROUND':'FIRST ROUND'}</span><h1>{screen==='practice'?`練習 ${practiceIndex+1} / 2`:`課題 ${(round?.index??0)+1} / 8`}</h1></div><button className="button ghost small-button" onClick={()=>changeTrial(t=>pauseTrial(t,Date.now(),'manual'))}>Ⅱ 一時停止</button></div><div className="progress-track" aria-label={`${screen==='practice'?practiceIndex:round?.index}課題完了`}><div style={{width:`${((screen==='practice'?practiceIndex:(round?.index??0))/(screen==='practice'?2:8))*100}%`}}/></div><div className="phase-steps"><span className={trial.phase==='reading'?'current':''}>01 説明を読む</span><i/><span className={trial.phase==='answering'?'current':''}>02 答える</span><i/><span className={trial.phase==='rating'?'current':''}>03 振り返る</span></div>
        {!trial.paused&&trial.phase!=='rating'&&<><p className="task-instruction">{trial.phase==='reading'?'自分のペースで説明を読んでください。読み終えたら、問題へ進みます。':'説明を見返しながら答えてください。回答は、確定するまで変更できます。'}</p><Passage trial={trial}/>{trial.phase==='reading'?<div className="read-action"><span className="small muted">設問を表示してからも、説明は残ります。</span><button className="button primary" onClick={readComplete}>問題に進む →</button></div>:<section id="questions" tabIndex={-1} className="questions"><div className="section-heading"><h2>説明を使って、答えてみよう。</h2><span>4 QUESTIONS</span></div>{getTask(trial.taskId).questions.map((q,qi)=><fieldset className="question" key={q.id}><legend><span className="question-number">{String(qi+1).padStart(2,'0')}</span>{q.prompt}</legend><div className="answer-options">{q.options.map((o,oi)=><label key={oi} className={trial.answers[qi]===oi?'selected':''}><input type="radio" name={q.id} checked={trial.answers[qi]===oi} onChange={()=>changeTrial(t=>({...t,answers:t.answers.map((a,i)=>i===qi?oi:a)}))}/><span>{o}</span></label>)}</div>{trial.answers[qi]!==null&&<button className="text-button small clear-answer" onClick={()=>changeTrial(t=>({...t,answers:t.answers.map((a,i)=>i===qi?null:a)}))}>選択を取り消す</button>}</fieldset>)}<div className="read-action"><span className="small muted">{trial.answers.filter(a=>a!==null).length} / 4 問に回答</span><button className="button primary" onClick={submitAnswers}>回答を確定する →</button></div></section>}</>}
        {!trial.paused&&trial.phase==='rating'&&<div className="rating-card"><div className="eyebrow">A QUICK REFLECTION</div><h2>いまの課題、どう感じましたか？</h2><p className="muted">正解はまだ表示しません。感じたまま、別々に答えてください。</p><Scale label="考えるために、どれくらい精神的な努力を使いましたか？" description="説明を読み、問題に答える間の感覚です。この試作独自の探索用質問です。" low="ほとんど使わなかった" high="とても多く使った" value={trial.effort} onChange={n=>changeTrial(t=>({...t,effort:n}))}/><Scale label="この説明の表示を、次も使いたいと思いますか？" low="まったく思わない" high="とても思う" value={trial.preference} onChange={n=>changeTrial(t=>({...t,preference:n}))}/><button className="button primary full" onClick={finish}>{screen==='practice'?'練習の答えを見る':round?.index===7?'今回の記録を見る':round?.index===3?'4課題を終えて、ひと休み':'次の課題へ'} →</button><p className="small muted centered">評定は未回答でも進めます。評定中の時間は測りません。</p></div>}
        {trial.paused&&<div className="pause-card"><span className="round-symbol" aria-hidden="true">Ⅱ</span><h2>ひと休みしましょう。</h2><p>説明を隠して、計時を止めています。<br/>準備ができたら、同じところから再開できます。</p>{trial.timingUncertain&&<p className="notice">再読み込みがあったため、この課題の時間は参考外として記録します。</p>}<button className="button primary" onClick={()=>changeTrial(t=>resumeTrial(t,Date.now()))}>再開する →</button><button className="text-button centered" onClick={goHome}>ホームに戻る</button></div>}
        {!trial.paused&&<div className="task-bottom"><button className="text-button small" onClick={()=>setConfirm('skip')} disabled={trial.phase==='rating'}>この課題を未完了として進む</button>{screen==='run'&&<button className="text-button small" onClick={()=>setConfirm('stop')}>ここまでの記録を見る</button>}</div>}
      </section>}
      {screen==='practiceFeedback'&&<section className="narrow flow-page"><div className="eyebrow">PRACTICE REVIEW</div><h1>流れを確かめよう。</h1><p className="lead">本番では、別日の再確認が終わるまで正解を表示しません。練習ではここで確認できます。</p><AnswerReview trial={practice}/><button className="button primary full" onClick={()=>{if(practiceIndex===0){setPracticeIndex(1);setPractice(startTrial(newTrial('practice-2','B'),Date.now()));setScreen('practice');}else setScreen('ready');}}>{practiceIndex===0?'もう1つ、表示を変えて練習':'本番へ進む'} →</button></section>}
      {screen==='run'&&breakOpen&&round&&<section className="narrow flow-page ready-page"><span className="round-symbol" aria-hidden="true">⌁</span><div className="eyebrow">HALFWAY THERE</div><h1>半分、おつかれさま。</h1><p className="lead">ここでひと休みしても、そのまま進んでも。<br/>休憩中の時間は測っていません。</p><div className="break-progress"><span>4 / 8</span><div className="progress-track"><div style={{width:'50%'}}/></div></div><button className="button primary full" onClick={()=>{updateRound(r=>({...r,trials:r.trials.map((t,i)=>i===r.index?startTrial(t,Date.now()):t)}));setBreakOpen(false);}}>残りの4課題へ →</button><button className="text-button centered" onClick={goHome}>保存して、いったん戻る</button></section>}
      {screen==='results'&&round&&<section className="results-page"><div className="results-top"><div><div className="eyebrow">YOUR OBSERVATIONS</div><h1>今回の、読み取りメモ。</h1><p className="lead">一つの点数にせず、いくつかの面から。</p></div><button className="button ghost" onClick={exportJson}>↓ JSONを書き出す</button></div><div className="result-meta"><span>{round.set==='initial'?'初回の比較':'未見セットでの再確認'}</span><span>{round.day}</span><span>{round.trials.filter(t=>t.phase==='done').length} / 8 課題完了</span></div><div className="result-notice"><strong>ここにあるのは、この課題での観測です。</strong><p>どちらが「最適」か、能力やタイプは判定しません。課題の難しさ、慣れ、順番による違いも残ります。少数の課題で差がないことは、同等の証明にはなりません。</p></div>{roundWarnings(round).map(w=><div className="notice" key={w}>{w}</div>)}
      <div className="result-grid">{(['A','B'] as const).map(c=>{const summary=conditionSummary(round,c);return <article className={`condition-card condition-${c}`} key={c}><div className="condition-heading"><span className="condition-letter">{c}</span><div><h2>{labels[c]}</h2><span className="small muted">{summary.count} / {summary.planned} 課題完了</span></div></div><div className="main-metric"><span>応用問題の正答 / 回答済み</span><strong>{formatScore(summary.applicationCorrect,summary.applicationAnswered)}<small>問</small></strong><span className="small muted">全12問のうち未回答・未確定 {summary.applicationMissing} 問</span></div><dl className="metric-list"><div><dt>内容確認の正答 / 回答済み</dt><dd>{formatScore(summary.retrievalCorrect,summary.retrievalAnswered)} <small>問</small></dd></div><div><dt>最初に読む時間 · 平均</dt><dd>{formatTime(summary.readingMs)}</dd></div><div><dt>解く時間 · 平均</dt><dd>{formatTime(summary.answeringMs)}</dd></div><div><dt>読む＋解く時間 · 平均</dt><dd>{formatTime(summary.totalMs)}</dd></div><div><dt>精神的な努力 · 平均</dt><dd>{summary.effort?.toFixed(1)??'—'} <small>/ 7（n={summary.effortN}）</small></dd></div><div><dt>次も使いたい · 平均</dt><dd>{summary.preference?.toFixed(1)??'—'} <small>/ 7（n={summary.preferenceN}）</small></dd></div></dl><p className="small muted">時間の集計対象：中断・未回答なしの{summary.timeN}課題。解く時間には説明の読み直しを含みます。</p></article>;})}</div><p className="small muted result-footnote">時間が短いこと、努力が小さいことだけで、理解が良いとは判断できません。正答の条件がそろわない時間比較は特に慎重に扱ってください。</p>
      <section className="pair-section"><div className="section-heading"><h2>対応する課題ごとに見る</h2><span>4 MATCHED PAIRS</span></div><p className="muted small">各ペアは似た推論の形ですが、難度が等しいと検証された教材ではありません。</p><div className="pair-table"><div className="pair-head"><span>課題ペア</span><span>A · 応用の正答</span><span>B · 応用の正答</span></div>{[...new Set(round.trials.map(t=>getTask(t.taskId).pairId))].map((pair,pi)=><div className="pair-row" key={pair}><span>ペア {pi+1}</span>{(['A','B'] as const).map(c=>{const t=round.trials.find(t=>getTask(t.taskId).pairId===pair&&t.condition===c)!;const s=scoreTrial(t).application;return <span key={c}><strong>{t.phase==='done'?formatScore(s.correct,s.answered):'未完了'}</strong><small>{getTask(t.taskId).title}</small>{t.interruptions.length>0&&<small>中断あり</small>}</span>;})}</div>)}</div></section>
      <section className="preference-section"><h2>振り返って、どちらの表示を使いたいですか？</h2><p className="muted small">好みを独立して残します。成績が良いことを意味するものではありません。</p><div className="preference-options">{([['A','連続した文章'],['B','区切った文章'],['same','どちらも同じくらい'],['unsure','まだわからない']] as const).map(([value,label])=><button className={round.overallPreference===value?'selected':''} key={value} onClick={()=>updateRound(r=>({...r,overallPreference:value}))}>{label}</button>)}</div></section>
      <section className="next-panel"><span className="round-symbol small-symbol" aria-hidden="true">↗</span><div><h2>{round.status!=='complete'?'続きは、準備ができたら。':!retest?'次は、別日の未見セットで。':'説明の設定は、まだ仮説として。'}</h2><p>{round.status!=='complete'?'未完了の記録です。途中から再開できます。':!retest?'新しい8課題でも、同じ傾向になるか確かめましょう。':'一般課題の傾向をコード理解へそのまま当てはめず、実際の作業で別に確かめましょう。'}</p>{round.status!=='complete'?<button className="button primary" onClick={()=>resumeRound(round)}>途中から再開 →</button>:canRetest?<button className="button primary" onClick={()=>setScreen('setup')}>未見セットで再確認 →</button>:!retest?<span className="small muted">再確認は、初回とは別の日に開始できます。</span>:<p className="small muted">設定候補の書き方：「短い架空ルール課題では、この形式を好んだ。理解面の効果は未検証。実作業で確認して見直す。」</p>}</div></section>
      {retest?.status==='complete'&&<section className="review-section"><button className="text-button" onClick={()=>setShowReview(!showReview)}>{showReview?'正解を閉じる':'この回の正解と解説を確認する'} {showReview?'−':'＋'}</button>{showReview&&round.trials.map(t=><div key={t.taskId}><h3>{getTask(t.taskId).title}</h3><AnswerReview trial={t}/></div>)}</section>}
      <div className="result-actions"><button className="text-button" onClick={goHome}>← ホームへ</button><button className="text-button muted" onClick={()=>setConfirm('reset')}>この端末の記録を削除</button></div></section>}
    </main>
    <footer className="site-footer"><span>explain fit <span className="footer-dot">·</span> 自分に合う説明を、小さく試す。</span><button className="text-button small" onClick={showPrivacy}>この試作について</button></footer>
    {privacy&&<Modal title="データの扱いと、この試作の限界" onClose={()=>setPrivacy(false)}><p>回答、日時、課題の割当、時間、中断、努力と好みの評定、表示領域のサイズを、このブラウザのlocalStorageに保存します。名前や健康・診断情報は集めません。</p><p>保存期間に自動の期限はありません。このアプリの「記録を削除」か、ブラウザのサイトデータ削除で消せます。ブラウザや端末を変えると記録は引き継がれません。シークレットモードでは保存が消える場合があります。</p><p>回答の外部送信、ログイン、外部解析、LLMによる採点はありません。アプリを公開した場合、配信元に通常のアクセスログが残る可能性はあります。JSONを書き出すと、回答・日時に加えて全課題と正解も含まれます。再確認前は正解を読まないでください。共有はご自身の判断で行ってください。</p><p>標準化・妥当化された検査ではありません。8課題・所要時間は試作の設計値です。1〜7の努力の質問も独自の探索用です。改行と余白以外の文言・順序・文字サイズ・表示幅をそろえていますが、別内容の課題の難度差は残ります。</p><p>最初に読む時間と、回答・読み直しの時間を分けて計測します。純粋な処理速度や記憶力は測定しません。中断、未回答、再読み込みを記録し、時間の集計対象から除きます。合計時間に評定・休憩の時間は含めません。</p><div className="modal-actions"><button className="button ghost" onClick={()=>{setPrivacy(false);setConfirm('reset');}}>記録を削除</button><button className="button primary" onClick={()=>setPrivacy(false)}>閉じる</button></div></Modal>}
    {confirm&&<Modal title={confirm==='reset'?'この端末の記録を削除しますか？':confirm==='stop'?'ここまでの記録を見ますか？':confirm==='skip'?'この課題を未完了として進みますか？':'未回答を残して進みますか？'} onClose={()=>setConfirm(null)}><p>{confirm==='reset'?'初回・再確認の回答、時間、評定をこのブラウザから削除します。元に戻せません。必要なら先にJSONを書き出してください。書き出したファイルは削除されません。':confirm==='stop'?'いまの課題は一時停止し、未完了の記録として表示します。あとから同じところへ戻れます。':confirm==='skip'?'回答済みの内容は残します。未回答は誤答に数えず、欠測として記録します。この課題には戻れません。':'未回答は誤答に数えず、欠測として記録します。確定すると、この課題の回答は変更できません。'}</p><div className="modal-actions"><button className="button ghost" onClick={()=>setConfirm(null)}>戻る</button><button className={`button ${confirm==='reset'?'danger':'primary'}`} onClick={()=>{if(confirm==='reset')reset();else if(confirm==='stop')stop();else{changeTrial(t=>advanceToRating(t,Date.now(),confirm==='skip'));setConfirm(null);}}}>{confirm==='reset'?'記録を削除する':confirm==='stop'?'ここまでを見る':'未回答を残して進む'}</button></div></Modal>}
  </div>;
}
function AnswerReview({trial}:{trial:Trial}) {const task=getTask(trial.taskId);return <div className="answer-review">{task.questions.map((q,i)=><div key={q.id}><span className={trial.answers[i]===q.correctIndex?'correct':'neutral'}>{trial.answers[i]===null?'未回答':trial.answers[i]===q.correctIndex?'正解':'不正解'}</span><h3>{i+1}. {q.prompt}</h3><p><strong>正解：{q.options[q.correctIndex]}</strong><br/>{q.explanation}</p></div>)}</div>;}
